import Head from "next/head";
import styles from "@/styles/Home.module.css";

import Navbar from "components/Navbar";
import Header from "../../containers/Header";
import TechnologySection from "../../containers/TechnologySection";
import ProjectsSection from "../../containers/ProjectsSection";
import BottomCTA from "../../containers/BottomCTA";
import Footer from "../../containers/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Head>
        <title>Dardan Dara Portfolio</title>
        <meta name='description' content='Frontend Developer Portfolio' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Header />
        <TechnologySection />
        <ProjectsSection />
        <BottomCTA />
        <Footer />
      </main>
    </>
  );
}
